sudo: false
language: python
python: 3.6

addons:
  apt:
    packages:
    - ncftp
    - pandoc
    - texlive-binaries
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-latex-extra
    - texlive-fonts-extra
    - texlive-lang-german
    - latex-xcolor

install:
    - pip install pelican bibtexparser
script:
    - make html-cv



